// src/app/modules/home/components/form-init/form-init.component.ts
import {Component} from '@angular/core';
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {ShippingStatusRequest} from "../../../../core/models/request";
import {ModalService} from "../../../../core/service/ui/modal.service";
import {GeneralModalComponent} from "../../../../shared/modal/general-modal/general-modal.component";
import {ModalProperties} from "../../../../core/models/ui/dto";

@Component({
  selector: 'form-init',
  templateUrl: './form-init.component.html',
  styleUrls: ['./form-init.component.scss']
})
export class FormInitComponent {
  public form: FormGroup;

  constructor(private modalService: ModalService) {
    this.form = new FormGroup({});
    this.form.addControl('code', new FormControl('', {validators: this.builderValidator(4, 4)}));
    this.form.addControl('tracking', new FormControl('', {validators: this.builderValidator(8, 8)}));
  }

  async save() {
    if (this.form.valid) {
      const code = this.form.get("code")?.value;
      const number = this.form.get("tracking")?.value;
      const order: ShippingStatusRequest = {
        code,
        number
      }

      let list: Array<ShippingStatusRequest>;
      const trackings = localStorage.getItem("trackings");
      if (!!trackings) {
        list = JSON.parse(trackings) as Array<ShippingStatusRequest>;
        const flag = !list.find(c => c.number === order.number);
        if (flag) list.push(order);
      } else list = [order];
      localStorage.setItem("trackings", JSON.stringify(list));
      location.reload();
    } else {
      const properties: ModalProperties = {title: 'Error', message: 'Porfavor ingresa los datos correctamente.'};
      const response = await this.modalService.modalConfirm(GeneralModalComponent, {properties});
      if (!response) this.modalService.hide();
    }
  }

  clear() {
    this.form.get("code")?.reset();
    this.form.get("tracking")?.reset();
  }

  getControl(name: string) {
    return this.form.get(name) as FormControl;
  }

  private builderValidator(min: number, max: number) {
    return [Validators.required, Validators.minLength(min), Validators.maxLength(max)];
  }
}

<div style="width: 100%">
  <form *ngIf="form" [formGroup]="form">
    <div class="general-form-header">
      <h1 style="color: white">
        Ingresar numero de seguimiento y codigo.
      </h1>
    </div>
    <div class="general-form-content">
      <p>
        Ingresa los datos de tu pedido shalom, te mostraremos su ruta actual, e iremos notificando el
        trayecto del mismo, via email.
      </p>
    </div>
    <div class="general-form-content">
      <shipping-shalom-input [type]="'number'"
                             [label]="'Numero de tracking'"
                             [control]="getControl('tracking')"/>

      <shipping-shalom-input [type]="'text'"
                             [label]="'Codigo de tracking'"
                             [control]="getControl('code')"/>
    </div>
    <div class="content-buttons">
      <shipping-shalom-button
        (click)="save()"
        [name]="'Guardar'"
        [colorName]="'white'"
        [colorContent]="'#ee2a2f'"/>
      <shipping-shalom-button
        (click)="clear()"
        [name]="'Limpiar'"
        [colorContent]="'white'"
        [colorName]="'#ee2a2f'"/>
    </div>
  </form>
</div>

// src/components/form-init/FormInit.tsx
import React, {ChangeEvent, useState} from 'react';
import CustomButton from "../custom-ui/CustomButton";
import {CustomInput} from "../custom-ui/CustomInput";
import {ShippingStatusRequest} from "../../core/model/request";

function FormInit() {
  const padding: string = '3.5% 5% 3.5% 5%';

  const [code, setCode] = useState<string>('');
  const [number, setNumber] = useState<string>('');

  const handleNumberChange = (e: ChangeEvent<HTMLInputElement>) => setNumber(e.target.value);
  const handleCodeChange = (e: ChangeEvent<HTMLInputElement>) => setCode(e.target.value);

  const saveOrder = () => {
    if (!!code && !!number) {
      let list: Array<ShippingStatusRequest>;
      const order = {code, number};
      const trackings = localStorage.getItem("trackings");
      if (!!trackings) {
        list = JSON.parse(trackings) as Array<ShippingStatusRequest>;
        const flag = !list.find(c => c.number === order.number);
        if (flag) {
          list.push(order);
        } else {
        }
      } else {
        list = [order];
      }
      localStorage.setItem("trackings", JSON.stringify(list));
    }
  }

  return (
    <>
      <div style={{width: '100%'}}>
        <div style={{
          padding: '.5%',
          textAlign: 'center',
          backgroundColor: '#ee2a2f',
        }}>
          <h1 style={{color: 'white'}}>
            Ingresar numero de seguimiento y codigo.
          </h1>
        </div>
        <div style={{padding}}>
          <p>
            Ingresa los datos de tu pedido shalom, te mostraremos su ruta actual, e iremos notificando el
            trayecto del mismo, via email.
          </p>
        </div>
        <div style={{padding}}>
          <CustomInput
            width={'90%'}
            type="number"
            value={number}
            label="Numero de seguimiento"
            onChange={handleNumberChange}
            placeholder="Por favor ingresa tu numero de seguimiento"
          />
          <CustomInput
            width={'20%'}
            type="text"
            value={code}
            label="Codigo de seguimiento"
            onChange={handleCodeChange}
            placeholder="Por favor ingresa tu codigo de seguimiento"
          />
        </div>
        <div style={{
          gap: '5%',
          display: 'flex',
          padding: '2% 5% 2% 5%',
          backgroundColor: 'white',
        }}>
          <CustomButton
            onClick={saveOrder}
            properties={{
              title: 'Guardar',
              titleColor: 'white',
              contentColor: '#ee2a2f'
            }}
          />
          <CustomButton
            onClick={() => {
              setCode("");
              setNumber("");
            }}
            properties={{
              title: 'Limpiar',
              titleColor: '#ee2a2f',
              contentColor: 'white'
            }}
          />
        </div>
      </div>
    </>
  );
}

export default FormInit;
